create table exchange_rate.rate
(
    id        bigint generated by default as identity
        primary key,
    char_code varchar(10)      not null,
    name      varchar(255)     not null,
    num_code  integer          not null,
    value     double precision not null,
    valute_id varchar(255)     not null
);
