create table exchange_rate.data_source
(
    id                integer generated by default as identity primary key,
    description       varchar(255) not null,
    source_short_name varchar(255) not null,
    source_url        varchar(255) not null
);
insert into exchange_rate.data_source (description, source_short_name, source_url)
values ('Источник - официальный сайт банка России',
        'CBR_RU_DAILY_ENG_XML',
        'https://www.cbr.ru/scripts/XML_daily_eng.asp?date_req='),
       ('Источник - некоммерческий проект, берут данные с cbr.ru',
        'CBR_NOT_OFFICIAL_XML_DAILY_RU_LATEST_JSON',
        'https://www.cbr-xml-daily.ru/latest.js');
