create table exchange_rate.exchange_rate
(
    id           bigint generated by default as identity
        primary key,
    currency     varchar(255) not null,
    date_rating  date         not null,
    time_request timestamp    not null,
    data_source  integer
        constraint fk_data_source references exchange_rate.data_source
);
