spring:
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: com.example.just_project.config.H2IdentifierNamingStrategy
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        globally-quoted-identifiers: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: "jdbc:h2:mem:~/cms_tvdb;MODE=MYSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1"
  liquibase:
    enabled: off

debug: true
