server:
  port: ${PORT:8085}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:}
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:just_project}?currentSchema=public
  liquibase:
    enabled: on
    change-log: db/changelog/db-master.xml
  jpa:
    generate-ddl: true

springdoc:
  packagesToScan: com.example.just_project
  swagger-ui:
    disable-swagger-default-url: true