--=============================================================================================================
/*
create table if not exists publisher
(
    id bigint generated by default as identity primary key, city  varchar(255) not null,
    title varchar(255) not null constraint uk_6iifkhmg1bm4skkakx6ix14sj unique
);alter table publisher owner to postgres;
create table if not exists book
(
    id bigint generated by default as identity primary key,
    isbn varchar(255) not null,title varchar(255) not null,publisher_id bigint not null
        constraint fkgtvt7p649s4x80y6f4842pnfq references publisher
);alter table book owner to postgres;
insert into publisher (city, title)
values ('Москва', 'Росмэн'),
       ('Санкт-Петербург', 'Махаон');

--drop table if exists book;
insert into book (title, isbn, publisher_id)
values ('Гарри Поттер и Философский камень', 'OZN163217492', 1),
       ('Гарри Поттер и Тайная комната', '978-5-389-07781-2', 2);
*/
--=============================================================================================================
select * from book b
join publisher p on p.id = b.publisher_id;
