create table exchange_rate.exchange_rate
(
    id           bigint generated by default as identity primary key,
    currency     varchar(255)  not null,
    date_rating  date          not null,
    data_source  varchar(255)  not null,
    rates        varchar(1024) not null,
    time_request timestamp     not null
);